# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab_Booking',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('cancellation_by', models.CharField(max_length=30)),
                ('cancellation_reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('car_no', models.CharField(max_length=10)),
                ('car_model', models.CharField(max_length=20)),
                ('car_type', models.CharField(max_length=20)),
                ('car_owner', models.CharField(max_length=40)),
                ('car_owner_address', models.TextField()),
                ('car_puc', models.TextField()),
                ('car_insurance_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cust_fname', models.CharField(max_length=30)),
                ('cust_lname', models.CharField(max_length=30)),
                ('cust_email', models.EmailField(max_length=40)),
                ('cust_phoneno', models.IntegerField()),
                ('secret', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driver_fname', models.CharField(max_length=30)),
                ('driver_lname', models.CharField(max_length=30)),
                ('driver_email', models.EmailField(max_length=40)),
                ('driver_phoneno', models.IntegerField()),
                ('driver_licence_no', models.CharField(max_length=15)),
                ('driver_address', models.TextField()),
                ('driver_police_verfication', models.CharField(max_length=25)),
                ('driver_years_exp', models.FloatField()),
                ('secret', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_lang', models.DecimalField(decimal_places=6, max_digits=9)),
                ('loc_lat', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Ride_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_fare', models.IntegerField()),
                ('parking_fare', models.IntegerField()),
                ('toll_charges', models.IntegerField()),
                ('payment_type', models.CharField(max_length=25)),
                ('cust_rating', models.IntegerField()),
                ('cust_comments', models.TextField()),
                ('total_time', models.FloatField()),
                ('booking_day', models.DateTimeField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_my_ride.Cab_Booking')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_my_ride.Driver'),
        ),
        migrations.AddField(
            model_name='cab_booking',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_my_ride.Customer'),
        ),
        migrations.AddField(
            model_name='cab_booking',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_my_ride.Driver'),
        ),
    ]
